"""Frozen V1 contracts shared by every module."""

from marx_engels.contracts.api import (
    ContextResponse,
    CorporaResponse,
    CorpusSummary,
    ErrorBody,
    ErrorResponse,
    FeedbackRequest,
    FeedbackResponse,
    HealthResponse,
    ModeSuggestionRequest,
    ModeSuggestionResponse,
    PdfLocationResponse,
    ReleaseMetadataResponse,
    ScopeNode,
    ScopeTreeResponse,
)
from marx_engels.contracts.enums import (
    AuthorCode,
    ContentType,
    DatePrecision,
    SearchMode,
    SupportLabel,
)
from marx_engels.contracts.search import (
    Candidate,
    Evidence,
    Insufficiency,
    ReleaseInfo,
    ResultGroup,
    SearchOptions,
    SearchOverview,
    SearchRequest,
    SearchResponse,
    SearchScope,
    Warning,
)

__all__ = [
    "AuthorCode",
    "Candidate",
    "ContentType",
    "ContextResponse",
    "CorporaResponse",
    "CorpusSummary",
    "DatePrecision",
    "ErrorBody",
    "ErrorResponse",
    "Evidence",
    "FeedbackRequest",
    "FeedbackResponse",
    "HealthResponse",
    "Insufficiency",
    "ModeSuggestionRequest",
    "ModeSuggestionResponse",
    "PdfLocationResponse",
    "ReleaseInfo",
    "ReleaseMetadataResponse",
    "ResultGroup",
    "ScopeNode",
    "ScopeTreeResponse",
    "SearchMode",
    "SearchOptions",
    "SearchOverview",
    "SearchRequest",
    "SearchResponse",
    "SearchScope",
    "SupportLabel",
    "Warning",
]
